// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/25/2024, 8:53:44 PM
const configMerger = require("C:/Users/Test/Desktop/Posao/flora/flora/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
(() => {const cfg=configMerger(undefined, require("./../tailwind.config.js"));cfg.content = cfg.purge;;return cfg;})()
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Test/Desktop/Posao/flora/flora/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/plugins/**/*.{js,ts,mjs}","C:/Users/Test/Desktop/Posao/flora/flora/composables/**/*.{js,ts,mjs}","C:/Users/Test/Desktop/Posao/flora/flora/utils/**/*.{js,ts,mjs}","C:/Users/Test/Desktop/Posao/flora/flora/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/app.config.{js,ts,mjs}"] }));

module.exports = config
