// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/19/2024, 5:42:57 PM
const configMerger = require("C:/Users/Test/Desktop/Posao/flora/flora/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Test/Desktop/Posao/flora/flora/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/plugins/**/*.{js,ts,mjs}","C:/Users/Test/Desktop/Posao/flora/flora/composables/**/*.{js,ts,mjs}","C:/Users/Test/Desktop/Posao/flora/flora/utils/**/*.{js,ts,mjs}","C:/Users/Test/Desktop/Posao/flora/flora/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Test/Desktop/Posao/flora/flora/app.config.{js,ts,mjs}"] }));

module.exports = config
